package com.android.joinme.ui.overview

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import com.android.joinme.model.map.Location
import org.junit.Rule
import org.junit.Test

/** Note: The tests were generated by IA (Claude) */

/**
 * Unit tests for EventForSerieFormScreen.
 *
 * Tests the reusable form component used by both Create and Edit event for serie screens. Focuses
 * on rendering, input behavior, and validation display without redundancy with screen-level tests.
 */
class EventForSerieFormScreenTest {

  @get:Rule val composeTestRule = createComposeRule()

  private val testTags =
      EventForSerieFormTestTags(
          inputEventType = "inputEventType",
          inputEventTitle = "inputEventTitle",
          inputEventDescription = "inputEventDescription",
          inputEventLocation = "inputEventLocation",
          inputEventLocationSuggestions = "inputEventLocationSuggestions",
          inputEventDuration = "inputEventDuration",
          buttonSaveEvent = "buttonSaveEvent",
          errorMessage = "errorMessage")

  // ---------- Basic Rendering ----------

  @Test
  fun allFieldsAreDisplayed() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventTitle).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventDescription).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventDuration).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventLocation).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.buttonSaveEvent).assertIsDisplayed()
  }

  @Test
  fun titleIsDisplayedCorrectly() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Custom Form Title",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Custom Form Title").assertIsDisplayed()
  }

  @Test
  fun saveButtonTextCanBeCustomized() {
    val formState =
        EventForSerieFormState(
            type = "SPORTS",
            title = "Test",
            description = "Desc",
            duration = "60",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = Location(1.0, 1.0, "Test"),
            isValid = true,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {},
          saveButtonText = "Update Event")
    }

    composeTestRule.onNodeWithText("Update Event").assertIsDisplayed()
  }

  // ---------- Form State Display ----------

  @Test
  fun formDisplaysStateValues() {
    val formState =
        EventForSerieFormState(
            type = "SPORTS",
            title = "Weekly Match",
            description = "Regular game",
            duration = "90",
            locationQuery = "EPFL",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).assertTextContains("SPORTS")
    composeTestRule.onNodeWithTag(testTags.inputEventTitle).assertTextContains("Weekly Match")
    composeTestRule
        .onNodeWithTag(testTags.inputEventDescription)
        .assertTextContains("Regular game")
    composeTestRule.onNodeWithTag(testTags.inputEventDuration).assertTextContains("90")
    composeTestRule.onNodeWithTag(testTags.inputEventLocation).assertTextContains("EPFL")
  }

  @Test
  fun saveButtonIsDisabledWhenFormInvalid() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.buttonSaveEvent).assertIsNotEnabled()
  }

  @Test
  fun saveButtonIsEnabledWhenFormValid() {
    val formState =
        EventForSerieFormState(
            type = "SPORTS",
            title = "Test Event",
            description = "Description",
            duration = "60",
            locationQuery = "EPFL",
            locationSuggestions = emptyList(),
            selectedLocation = Location(1.0, 1.0, "EPFL"),
            isValid = true,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.buttonSaveEvent).assertIsEnabled()
  }

  // ---------- Validation Error Display ----------

  @Test
  fun validationErrorsAreDisplayed() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = "Type cannot be empty",
            invalidTitleMsg = "Title cannot be empty",
            invalidDescriptionMsg = "Description cannot be empty",
            invalidDurationMsg = "Must be a positive number",
            invalidLocationMsg = "Must be a valid Location")

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Type cannot be empty").assertIsDisplayed()
    composeTestRule.onNodeWithText("Title cannot be empty").assertIsDisplayed()
    composeTestRule.onNodeWithText("Description cannot be empty").assertIsDisplayed()
    composeTestRule.onNodeWithText("Must be a positive number").assertIsDisplayed()
    composeTestRule.onNodeWithText("Must be a valid Location").assertIsDisplayed()
  }

  // ---------- User Interactions ----------

  @Test
  fun typeDropdownOpensAndSelectsValue() {
    var selectedType = ""
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = { selectedType = it },
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).performClick()
    composeTestRule.onNodeWithText("ACTIVITY").assertIsDisplayed()
    composeTestRule.onNodeWithText("ACTIVITY").performClick()

    assert(selectedType == "ACTIVITY")
  }

  @Test
  fun titleInputTriggersCallback() {
    var changedTitle = ""
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = { changedTitle = it },
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventTitle).performTextInput("New Title")

    assert(changedTitle.contains("New Title"))
  }

  @Test
  fun durationDialogOpensAndConfirms() {
    var selectedDuration = ""
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "60",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = { selectedDuration = it },
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventDuration).performClick()
    composeTestRule.onNodeWithText("Select Duration (min)").assertIsDisplayed()
    composeTestRule.onNodeWithText("OK").performClick()

    assert(selectedDuration.isNotEmpty())
  }

  @Test
  fun durationDialogCanBeCancelled() {
    var selectedDuration = ""
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "60",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = { selectedDuration = it },
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventDuration).performClick()
    composeTestRule.onNodeWithText("Cancel").performClick()

    // Duration should not have changed
    assert(selectedDuration.isEmpty())
  }

  @Test
  fun  locationSuggestionsAreDisplayed() {
    val suggestions =
        listOf(
            Location(1.0, 1.0, "Rolex Learning Center"),
            Location(2.0, 2.0, "BC Building"),
            Location(3.0, 3.0, "SwissTech Convention Center"))

    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "EPFL",
            locationSuggestions = suggestions,
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    // Verify all unique suggestion texts are displayed
    composeTestRule.onNodeWithText("Rolex Learning Center").assertIsDisplayed()
    composeTestRule.onNodeWithText("BC Building").assertIsDisplayed()
    composeTestRule.onNodeWithText("SwissTech Convention Center").assertIsDisplayed()
  }

  @Test
  fun allEventTypesAreAvailableInDropdown() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).performClick()

    composeTestRule.onNodeWithText("SPORTS").assertIsDisplayed()
    composeTestRule.onNodeWithText("ACTIVITY").assertIsDisplayed()
    composeTestRule.onNodeWithText("SOCIAL").assertIsDisplayed()
  }

  @Test
  fun backButtonTriggersCallback() {
    var backCalled = false
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = { backCalled = true })
    }

    composeTestRule.onNodeWithContentDescription("Back").performClick()

    assert(backCalled)
  }

  @Test
  fun typeValidationErrorIsDisplayed() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = "Event type cannot be empty",
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Event type cannot be empty").assertIsDisplayed()
  }

  @Test
  fun durationValidationErrorIsDisplayed() {
    val formState =
        EventForSerieFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            isValid = false,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = "Must be a positive number",
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Must be a positive number").assertIsDisplayed()
  }
}
