package com.android.joinme.ui.overview

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/** Note: This file was generated by AI (Claude) */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28], qualifiers = "w360dp-h640dp-normal-long-notround-any-420dpi-keyshidden-nonav")
class EditEventForSerieScreenTest {

  @get:Rule val composeTestRule = createComposeRule()

  /** --- BASIC RENDERING --- */
  @Test
  fun allFieldsAndButtonAreDisplayed() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TYPE)
        .assertIsDisplayed()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .assertIsDisplayed()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .assertIsDisplayed()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DURATION)
        .assertIsDisplayed()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .assertIsDisplayed()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.BUTTON_SAVE_EVENT)
        .assertIsDisplayed()
  }

  @Test
  fun titleAndButtonTextAreCorrect() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule.onNodeWithText("Edit Event for Serie").assertIsDisplayed()
    composeTestRule.onNodeWithText("Save Changes").assertIsDisplayed()
  }

  /** --- INPUT BEHAVIOR --- */
  @Test
  fun typeDropdownWorks() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule.onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TYPE).performClick()

    composeTestRule.onNodeWithText("SPORTS").assertIsDisplayed()
    composeTestRule.onNodeWithText("SPORTS").performClick()

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TYPE)
        .assertTextContains("SPORTS")
  }

  @Test
  fun textFieldsAcceptInput() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    val title = "Updated Football Match"
    val desc = "Updated description"
    val location = "New Location"

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextInput(title)

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .performTextInput(desc)

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .performTextInput(location)

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .assertTextContains(title)
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .assertTextContains(desc)
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .assertTextContains(location)
  }

  @Test
  fun allEventTypesAreAvailable() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule.onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TYPE).performClick()

    composeTestRule.onNodeWithText("SPORTS").assertIsDisplayed()
    composeTestRule.onNodeWithText("ACTIVITY").assertIsDisplayed()
    composeTestRule.onNodeWithText("SOCIAL").assertIsDisplayed()
  }

  /** --- VALIDATION BEHAVIOR --- */
  @Test
  fun emptyTitleDisablesSaveButton() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextClearance()

    composeTestRule.waitForIdle()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.BUTTON_SAVE_EVENT)
        .assertIsNotEnabled()
  }

  @Test
  fun whitespaceInputsShouldBeTreatedAsEmpty() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextInput("   ")

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .performTextInput("   ")

    composeTestRule.waitForIdle()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.BUTTON_SAVE_EVENT)
        .assertIsNotEnabled()
  }

  @Test
  fun switchingTypeRetainsOtherFields() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    val title = "Morning Run"
    val desc = "Light jog near EPFL"

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .performTextInput(title)

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .performTextInput(desc)

    composeTestRule.onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TYPE).performClick()
    composeTestRule.onNodeWithText("SPORTS").performClick()

    composeTestRule.onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TYPE).performClick()
    composeTestRule.onNodeWithText("SOCIAL").performClick()

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_TITLE)
        .assertTextContains(title)
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DESCRIPTION)
        .assertTextContains(desc)
  }

  /** --- EDIT-SPECIFIC BEHAVIOR --- */
  @Test
  fun durationPickerOpensOnClick() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_DURATION)
        .performClick()

    composeTestRule.onNodeWithText("Select Duration (min)").assertIsDisplayed()
  }

  @Test
  fun locationFieldAcceptsInput() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    val location = "Rolex Learning Center"
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .performTextClearance()
    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .performTextInput(location)

    composeTestRule
        .onNodeWithTag(EditEventForSerieScreenTestTags.INPUT_EVENT_LOCATION)
        .assertTextContains(location)
  }

  @Test
  fun fieldsNotInheritedFromSerieAreNotDisplayed() {
    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = "testSerieId", eventId = "testEventId", onDone = {})
    }

    composeTestRule
        .onNodeWithTag("inputEventMaxParticipants", useUnmergedTree = true)
        .assertDoesNotExist()
    composeTestRule.onNodeWithTag("inputEventDate", useUnmergedTree = true).assertDoesNotExist()
    composeTestRule.onNodeWithTag("inputEventTime", useUnmergedTree = true).assertDoesNotExist()
    composeTestRule
        .onNodeWithTag("inputEventVisibility", useUnmergedTree = true)
        .assertDoesNotExist()
  }

  @Test
  fun eventIdAndSerieIdArePassedCorrectly() {
    val testSerieId = "unique-serie-id-123"
    val testEventId = "unique-event-id-456"

    composeTestRule.setContent {
      EditEventForSerieScreen(serieId = testSerieId, eventId = testEventId, onDone = {})
    }

    composeTestRule.onNodeWithTag(EditEventForSerieScreenTestTags.BUTTON_SAVE_EVENT).assertExists()
  }
}
