package com.android.joinme.ui.overview

import android.content.Context
import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.test.core.app.ApplicationProvider
import com.android.joinme.model.map.Location
import com.google.firebase.FirebaseApp
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/** Note: The tests were generated by IA (Claude) */

/**
 * Unit tests for EventForSerieFormScreen.
 *
 * Tests the reusable form component used by both Create and Edit event for serie screens. Focuses
 * on rendering, input behavior, and validation display without redundancy with screen-level tests.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28], qualifiers = "w360dp-h640dp-normal-long-notround-any-420dpi-keyshidden-nonav")
class EventForSerieFormScreenTest {

  @get:Rule val composeTestRule = createComposeRule()

  @Before
  fun setUp() {
    // Initialize Firebase for Robolectric tests
    val context = ApplicationProvider.getApplicationContext<Context>()
    if (FirebaseApp.getApps(context).isEmpty()) {
      FirebaseApp.initializeApp(context)
    }
  }

  private val testTags =
      EventForSerieFormTestTags(
          inputEventType = "inputEventType",
          inputEventTitle = "inputEventTitle",
          inputEventDescription = "inputEventDescription",
          inputEventLocation = "inputEventLocation",
          inputEventLocationSuggestions = "inputEventLocationSuggestions",
          inputEventDuration = "inputEventDuration",
          buttonSaveEvent = "buttonSaveEvent",
          errorMessage = "errorMessage",
          forEachInputEventLocationSuggestion = "forEachInputEventLocationSuggestion")

  /** Helper function to create a test form state. */
  private fun createTestFormState(
      type: String = "",
      title: String = "",
      description: String = "",
      duration: String = "",
      location: String = "",
      locationQuery: String = "",
      locationSuggestions: List<Location> = emptyList(),
      selectedLocation: Location? = null,
      isLoading: Boolean = false,
      errorMsg: String? = null,
      invalidTypeMsg: String? = null,
      invalidTitleMsg: String? = null,
      invalidDescriptionMsg: String? = null,
      invalidDurationMsg: String? = null,
      invalidLocationMsg: String? = null
  ): EventForSerieFormState {
    return EventForSerieFormState(
        type = type,
        title = title,
        description = description,
        duration = duration,
        location = location,
        locationQuery = locationQuery,
        locationSuggestions = locationSuggestions,
        selectedLocation = selectedLocation,
        isLoading = isLoading,
        errorMsg = errorMsg,
        invalidTypeMsg = invalidTypeMsg,
        invalidTitleMsg = invalidTitleMsg,
        invalidDescriptionMsg = invalidDescriptionMsg,
        invalidDurationMsg = invalidDurationMsg,
        invalidLocationMsg = invalidLocationMsg)
  }

  // ---------- Basic Rendering ----------

  @Test
  fun screenTitleAndAllFieldsAreDisplayed() {
    val formState = createTestFormState()

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Custom Form Title",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    // Verify screen title
    composeTestRule.onNodeWithText("Custom Form Title").assertIsDisplayed()

    // Verify all input fields
    composeTestRule.onNodeWithTag(testTags.inputEventType).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventTitle).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventDescription).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventDuration).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.inputEventLocation).assertIsDisplayed()
    composeTestRule.onNodeWithTag(testTags.buttonSaveEvent).assertIsDisplayed()
  }

  @Test
  fun saveButtonTextCanBeCustomized() {
    val formState =
        createTestFormState(
            type = "SPORTS",
            title = "Test",
            description = "Desc",
            duration = "60",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = Location(1.0, 1.0, "Test"),
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {},
          saveButtonText = "Update Event")
    }

    composeTestRule.onNodeWithText("Update Event").assertIsDisplayed()
  }

  // ---------- Form State Display ----------

  @Test
  fun formDisplaysStateValues() {
    val formState =
        createTestFormState(
            type = "SPORTS",
            title = "Weekly Match",
            description = "Regular game",
            duration = "90",
            locationQuery = "EPFL",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).assertTextContains("SPORTS")
    composeTestRule.onNodeWithTag(testTags.inputEventTitle).assertTextContains("Weekly Match")
    composeTestRule.onNodeWithTag(testTags.inputEventDescription).assertTextContains("Regular game")
    composeTestRule.onNodeWithTag(testTags.inputEventDuration).assertTextContains("90")
    composeTestRule.onNodeWithTag(testTags.inputEventLocation).assertTextContains("EPFL")
  }

  @Test
  fun saveButtonIsDisabledWhenFormInvalid() {
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.buttonSaveEvent).assertIsNotEnabled()
  }

  @Test
  fun saveButtonIsEnabledWhenFormValid() {
    val formState =
        createTestFormState(
            type = "SPORTS",
            title = "Test Event",
            description = "Description",
            duration = "60",
            locationQuery = "EPFL",
            locationSuggestions = emptyList(),
            selectedLocation = Location(1.0, 1.0, "EPFL"),
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.buttonSaveEvent).assertIsEnabled()
  }

  // ---------- Validation Error Display ----------

  @Test
  fun validationErrorsAreDisplayed() {
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = "Type cannot be empty",
            invalidTitleMsg = "Title cannot be empty",
            invalidDescriptionMsg = "Description cannot be empty",
            invalidDurationMsg = "Must be a positive number",
            invalidLocationMsg = "Must be a valid Location")

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Type cannot be empty").assertIsDisplayed()
    composeTestRule.onNodeWithText("Title cannot be empty").assertIsDisplayed()
    composeTestRule.onNodeWithText("Description cannot be empty").assertIsDisplayed()
    composeTestRule.onNodeWithText("Must be a positive number").assertIsDisplayed()
    composeTestRule.onNodeWithText("Must be a valid Location").assertIsDisplayed()
  }

  // ---------- User Interactions ----------

  @Test
  fun typeDropdownOpensAndSelectsValue() {
    var selectedType = ""
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = { selectedType = it },
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).performClick()
    composeTestRule.onNodeWithText("ACTIVITY").assertIsDisplayed()
    composeTestRule.onNodeWithText("ACTIVITY").performClick()

    assert(selectedType == "ACTIVITY")
  }

  @Test
  fun titleInputTriggersCallback() {
    var changedTitle = ""
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = { changedTitle = it },
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventTitle).performTextInput("New Title")

    assert(changedTitle.contains("New Title"))
  }

  @Test
  fun durationDialogOpensAndConfirms() {
    var selectedDuration = ""
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "60",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = { selectedDuration = it },
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventDuration).performClick()
    composeTestRule.onNodeWithText("Select Duration (min)").assertIsDisplayed()
    composeTestRule.onNodeWithText("OK").performClick()

    assert(selectedDuration.isNotEmpty())
  }

  @Test
  fun durationDialogCanBeCancelled() {
    var selectedDuration = ""
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "60",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = { selectedDuration = it },
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventDuration).performClick()
    composeTestRule.onNodeWithText("Cancel").performClick()

    // Duration should not have changed
    assert(selectedDuration.isEmpty())
  }

  @Test
  fun locationSuggestionsAreDisplayed() {
    val suggestions =
        listOf(
            Location(1.0, 1.0, "Rolex Learning Center"),
            Location(2.0, 2.0, "BC Building"),
            Location(3.0, 3.0, "SwissTech Convention Center"))

    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "EPFL",
            locationSuggestions = suggestions,
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Rolex Learning Center").assertExists()
    composeTestRule.onNodeWithText("BC Building").assertExists()
    composeTestRule.onNodeWithText("SwissTech Convention Center").assertExists()
  }

  @Test
  fun allEventTypesAreAvailableInDropdown() {
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithTag(testTags.inputEventType).performClick()

    composeTestRule.onNodeWithText("SPORTS").assertIsDisplayed()
    composeTestRule.onNodeWithText("ACTIVITY").assertIsDisplayed()
    composeTestRule.onNodeWithText("SOCIAL").assertIsDisplayed()
  }

  @Test
  fun backButtonTriggersCallback() {
    var backCalled = false
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = { backCalled = true })
    }

    composeTestRule.onNodeWithContentDescription("Back").performClick()

    assert(backCalled)
  }

  @Test
  fun typeValidationErrorIsDisplayed() {
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = "Event type cannot be empty",
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Event type cannot be empty").assertIsDisplayed()
  }

  @Test
  fun durationValidationErrorIsDisplayed() {
    val formState =
        createTestFormState(
            type = "",
            title = "",
            description = "",
            duration = "",
            locationQuery = "",
            locationSuggestions = emptyList(),
            selectedLocation = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = "Must be a positive number",
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    composeTestRule.onNodeWithText("Must be a positive number").assertIsDisplayed()
  }

  /** --- CONDITIONAL TYPE FIELD RENDERING TESTS --- */
  @Test
  fun typeField_withSerieHasGroupTrue_showsPlainText() {
    val formState =
        EventForSerieFormState(
            serieHasGroup = true, // Serie has a group
            type = "SPORTS", // Type is set from group
            title = "",
            description = "",
            duration = "",
            location = "",
            selectedLocation = null,
            locationQuery = "",
            locationSuggestions = emptyList(),
            isLoading = false,
            errorMsg = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    // Should show label and plain text, not a dropdown
    composeTestRule.onNodeWithText("Event Type (from Group)").assertIsDisplayed()
    composeTestRule.onNodeWithText("SPORTS").assertIsDisplayed()

    // Verify it's not a clickable dropdown - the test tag should still exist
    composeTestRule.onNodeWithTag(testTags.inputEventType).assertExists()
  }

  @Test
  fun typeField_withSerieHasGroupFalse_showsDropdown() {
    val formState =
        EventForSerieFormState(
            serieHasGroup = false, // Standalone serie
            type = "", // Type not set
            title = "",
            description = "",
            duration = "",
            location = "",
            selectedLocation = null,
            locationQuery = "",
            locationSuggestions = emptyList(),
            isLoading = false,
            errorMsg = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    // Should show dropdown field, not plain text with "from Group" label
    composeTestRule.onNodeWithTag(testTags.inputEventType).assertExists()
    composeTestRule.onNodeWithText("Event Type (from Group)").assertDoesNotExist()
  }

  @Test
  fun typeField_withSerieHasGroupTrue_displaysCorrectType() {
    val formState =
        EventForSerieFormState(
            serieHasGroup = true,
            type = "ACTIVITY", // Group has ACTIVITY type
            title = "",
            description = "",
            duration = "",
            location = "",
            selectedLocation = null,
            locationQuery = "",
            locationSuggestions = emptyList(),
            isLoading = false,
            errorMsg = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    // Should show the type from the group
    composeTestRule.onNodeWithText("Event Type (from Group)").assertIsDisplayed()
    composeTestRule.onNodeWithText("ACTIVITY").assertIsDisplayed()
  }

  @Test
  fun typeField_withSerieHasGroupTrue_isNotInteractive() {
    val formState =
        EventForSerieFormState(
            serieHasGroup = true,
            type = "SOCIAL",
            title = "",
            description = "",
            duration = "",
            location = "",
            selectedLocation = null,
            locationQuery = "",
            locationSuggestions = emptyList(),
            isLoading = false,
            errorMsg = null,
            invalidTypeMsg = null,
            invalidTitleMsg = null,
            invalidDescriptionMsg = null,
            invalidDurationMsg = null,
            invalidLocationMsg = null)

    composeTestRule.setContent {
      EventForSerieFormScreen(
          title = "Test Form",
          formState = formState,
          isFormValid = formState.isValid,
          testTags = testTags,
          onTypeChange = {},
          onTitleChange = {},
          onDescriptionChange = {},
          onDurationChange = {},
          onLocationQueryChange = {},
          onLocationSelected = {},
          onSearchLocations = {},
          onSave = { true },
          onGoBack = {})
    }

    // The type field should be plain text, not clickable
    // Verify the text exists
    composeTestRule.onNodeWithText("SOCIAL").assertIsDisplayed()

    // Note: We can't easily test that it's NOT clickable in Compose tests
    // But we verify it's rendered as Text, not a clickable field
  }
}
