package com.android.joinme.model.chat

/**
 * Utility functions for chat operations.
 */
object ChatUtils {
  /**
   * Generates a deterministic conversation ID for a direct message between two users.
   *
   * The ID is generated by sorting the user IDs alphabetically and combining them with the "dm_"
   * prefix. This ensures that regardless of which user initiates the conversation, the same
   * conversation ID is used.
   *
   * Format: "dm_{minUserId}_{maxUserId}"
   *
   * @param userId1 The first user's ID
   * @param userId2 The second user's ID
   * @return A deterministic conversation ID for the direct message
   * @throws IllegalArgumentException if either user ID is blank or if the IDs are identical
   */
  fun generateDirectMessageId(userId1: String, userId2: String): String {
    require(userId1.isNotBlank()) { "userId1 cannot be blank" }
    require(userId2.isNotBlank()) { "userId2 cannot be blank" }
    require(userId1 != userId2) { "Cannot create direct message with yourself" }

    val sortedIds = listOf(userId1, userId2).sorted()
    return "dm_${sortedIds[0]}_${sortedIds[1]}"
  }
}
